### ISSUE TITLE
Release 5.0.1 introduced breaking change compared to 5.0.0

### ISSUE THREAD

**Issue by rincedd** [algolia/react-element-to-jsx-string#62] opened 2016-11-17 17:36 UTC
In release 5.0.1 the dependency on `stringify-object` has been upgraded from `^2.3.1` to `3.0.0`. This is a breaking change, as `stringify-object@3.0.0` dropped support for Node 0.12 and 0.13, now relying on basic ES6 features such as `const`. In fact, this also means that `react-element-to-jsx-string` does not work in PhantomJS anymore without explicitly transpiling its dependencies to ES5. This also affects `chai-enzyme`, for instance.

I would suggest making this kind of upgrade only within major version changes to avoid such problems. Do you think you could come up with a fix? Is `stringify-object@3.0.0` really required at the moment?

**Comment by pleunv** [comment] 2016-11-17 19:46
Ran into the same problem earlier today, eventually downgraded `chai-enzyme` to 0.4.8 for now as I see no easy way to get webpack/babel to skip transpiling all node_modules except for `stringify-object`.
I'm not sure what the proper way to deal with issues like this is... many backend-focused libraries might be jumping the ES2015 bandwagon and stop providing ES5-compatible build outputs, which will **severely** impact frontend builds.

**Comment by vvo** [comment] 2016-11-17 20:47
Fixed by releasing 5.0.2, cc @neoziro

PS: Using PhantomJS as a regression test platform is dangerous, it represents 0% of the human browser market.

**Closed by vvo** 2016-11-17 20:47 UTC

**Comment by neoziro** [comment] 2016-11-17 20:49
@vvo I know that PhantomJS isn't a good solution, but it is comparable to jsdom.

**Comment by vvo** [comment] 2016-11-17 20:54
We use jsdom, it's better because you actually focus on your code path issues, not on weird unsupported API from an old webkit. jsdom comes by default with jest now

**Comment by rincedd** [comment] 2016-11-18 09:38
Thanks a lot for the quick fix. I agree that PhanotmJS isn't a good solution, which is why we also run the tests in our targeted browsers (Safari and IE in our case). The tests run in PhantomJS on the developers' machines before they push code changes, because the developers typically do not use our targeted browsers.

**Comment by vvo** [comment] 2016-11-18 10:26
Try jsDom, it should support what phantomJS support and is easier to debug
