### ISSUE TITLE
Can't run on react-addons-test-utils@15.4.0-rc.3

### ISSUE THREAD

**Issue by wellyshen** [algolia/react-element-to-jsx-string#56] opened 2016-11-05 19:03 UTC
Hi I update my react-addons-test-utils to 15.4.0-rc.3, that the error occurs when I run `npm test`.

> ERROR in .//react-element-to-jsx-string//react-addons-test-utils/index.js
Module not found: Error: Can't resolve 'react/lib/ReactTestUtils' in '/Users/Welly/Desktop/react-cool-starter/node_modules/react-element-to-jsx-string/node_modules/react-addons-test-utils'
@ .//react-element-to-jsx-string//react-addons-test-utils/index.js 1:17-52
@ .//react-element-to-jsx-string/index-dist.js
@ .//chai-enzyme/build/assertions/contain.js
@ ./~/chai-enzyme/build/index.js
@ ./tools/testing/test-bundler.js

Any solution for this?

**Comment by vvo** [comment] 2016-11-07 09:22
I guess they moved some files away to another package maybe? Have a look at react release notes or wait for an official release. Then we will have to update the files somehow

**Comment by vvo** [comment] 2016-11-14 20:21
Once this is out and not in RC we can upgrade the library, no idea how untill we get a proper changelog

**Comment by Spy-Seth** [comment] 2016-11-16 16:22
React 15.4 is out https://facebook.github.io/react/blog/2016/11/16/react-v15.4.0.html

The issue is still present with this last version of react and the last version of the lib (v5.0.0):

```
Cannot find module 'react/lib/ReactTestUtils' from 'index.js'

      at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:151:17)
      at Object.<anonymous> (node_modules/react-addons-test-utils/index.js:1:107)
      at Object.<anonymous> (node_modules/react-element-to-jsx-string/index-dist.js:23:29)
```

**Comment by ayrton** [comment] 2016-11-16 18:06
> However, there is a possibility that you imported private APIs from react/lib/*, or that a package you rely on might use them. We would like to remind you that this was never supported, and that your apps should not rely on internal APIs. The React internals will keep changing as we work to make React better.

**Comment by vvo** [comment] 2016-11-16 20:40
Nowhere in the code we try to access "react/lib/ReactTestUtils" so there's something else going on here.

**Comment by vvo** [comment] 2016-11-16 20:42
The only line about react-addons-test-utils is this: https://github.com/algolia/react-element-to-jsx-string/blob/c65d907a4c1c7a8b18b0b10e2581724b8394c0bf/index.js

**Comment by vvo** [comment] 2016-11-16 21:16
Here's the issue: https://github.com/facebook/react/issues/8314

**Comment by vvo** [comment] 2016-11-16 21:22
I wonder if react-dom should be a direct dependency instead, what do you think?

**Comment by vvo** [comment] 2016-11-16 21:29
should be fixed in 5.0.1, let me know

**Closed** 2016-11-16 21:29 UTC

**Comment by gaearon** [comment] 2016-11-17 00:04
For future reference please report issues in RCs to us :-). This is the reason we publish them.

**Comment by vvo** [comment] 2016-11-17 08:46
@gaearon What happened here is that given the error message we got ("Can't resolve 'react/lib/ReactTestUtils'" I thought that it was only a matter of updating some /path/ in the code, while the root issue was that react-addons-test-utils was no more working.

I understand your point about testing RCs but this open source project is part of what we do at Algolia and has lower priority than our core business. That's why we did not investigate a lot and missed an opportunity to raise a breaking change in react-addons-test-utils.

**Comment by vvo** [comment] 2016-11-17 08:52
@Spy-Seth I saw you :-1: the comment "Once this is out and not in RC we can upgrade the library, no idea how untill we get a proper changelog". I can understand your frustration but remember this is an open source library and in such anyone can contribute to it. From opening issues to fixing a bug.

It took 10 minutes to figure out the root cause so I would recommend anyone opening issues on any open source project to also have a quick look if they can actually fix the issue or dig a bit more into it and find the root cause.

4 people including me participated in this issue and no one took the necessary 10 minutes to run the code and dig it. We are the authors but it does not imply we will fix every bug or add every feature for you, you have to participate.

**Comment by Spy-Seth** [comment] 2016-11-17 09:37
@vvo I'm sorry if I've hurt you with my 👎 I will try to explain me.

We all do open source here, we know the rule: help and be helped. And like you said, we all have a limited time: you have limited to maintain the library, I have limited to debug library that I use.

I put the 👎  because I think it's not a good message spread. As a library author we have to follow our dependencies and check the incompatibilities against RC. And again, this is the perfect state of the art. I was not judging the fact you do not do it, I judge the message.

And by the way, your library helps us a lot 👍 thanks you for that.

**Comment by Spy-Seth** [comment] 2016-11-17 09:37
And by the way the fix works :)

**Comment by ericmasiello** [comment] 2017-06-07 13:09
I'm seeing this same issue. I'm currently using React and React DOM 15.4.2.

This is producing the following error when I attempt to bundle my code:

```
ERROR in ./~/react-element-to-jsx-string/index-dist.js
Module not found: Error: Can't resolve 'react-dom/test-utils' in '/Users/eric/Sites/stencil/node_modules/react-element-to-jsx-string'
```

**Comment by gaearon** [comment] 2017-06-07 13:15
>I'm seeing this same issue.

This is not the same issue (notice the module name is different from the one in the thread).
Please update to React 15.5.4, and it will be fixed.
