### ISSUE TITLE
Event handler not triggered

### ISSUE THREAD

**Issue by Suguru-Tokuda** [algolia/react-element-to-jsx-string#364] opened 2019-05-20 16:01 UTC
I'm using the library to render element to string values to pass into data-content for popover. I set onClick event handler for the element, however, the event handler is not triggered for onClick.

```
const links = dataset.map(data => <li key={data.val}>{data.val}</li>);
const linkList = reactElementToJSXString(<ul>{links}</ul>, { showFunctions: true });

return <li data-content={linkList} ...
```

**Comment by Spy-Seth** [comment] 2019-09-18 09:26
Without more context we could not reproduce. I'm closing it for now. If you have context for us I will reopen it

**Closed by Spy-Seth** 2019-09-18 09:26 UTC
